### ISSUE TITLE
Create an empty `application.properties`

### ISSUE THREAD

**Issue by snicoll** [spring-guides/gs-spring-data-reactive-redis#1]
A person on gitter got confused as they were starting with this and they have redis on a different host. Documentation mentions `application.properties` but the file doesn't exist here.

It would be nice if there was one. Perhaps with a few typical commented out properties?

**Comment by monotonewang** [comment]
https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/appendix-application-properties.html#data-properties

**Comment by Buzzardo** [comment]
The readme no longer mentions application.properties.
