### ISSUE TITLE
It will be great to have all crud operations in this tutorial 

### ISSUE THREAD

**Issue by salaboy** [spring-guides/gs-spring-data-reactive-redis#10]
This controller only implements all()

https://github.com/spring-guides/gs-spring-data-reactive-redis/blob/main/complete/src/main/java/hello/CoffeeController.java#L17

It will be great to have also `create`, `update` and `delete` too, as well as `getById`

**Comment by Buzzardo** [comment]
We try to keep the guides down to 15 minutes, so we can't fit that material in. It would make a great blog post to share with the community.
